<a href="https://colab.research.google.com/github/Keyrama/Machine-Learning/blob/main/Keras_ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.15.0


In [2]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

11490434/11490434 [==============================] - 1s 0us/step


In [14]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(64, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(32, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10, activation="softmax")
])

In [15]:
predictions = model(x_train[:1]).numpy()
predictions

array([[0.05530435, 0.10899866, 0.06259409, 0.08033098, 0.16927093,
        0.06369355, 0.20416042, 0.11901479, 0.05913225, 0.07749998]],
      dtype=float32)

In [5]:
#tf.nn.softmax(predictions).numpy()

array([[0.08408269, 0.06544694, 0.07365703, 0.15335064, 0.12709115,
        0.10679632, 0.085416  , 0.0692711 , 0.0467931 , 0.188095  ]],
      dtype=float32)

In [16]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
loss_fn(y_train[:1], predictions).numpy()
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])


In [17]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5


/usr/local/lib/python3.10/dist-packages/keras/src/backend.py:5727: UserWarning: "`sparse_categorical_crossentropy` received `from_logits=True`, but the `output` argument was produced by a Softmax activation and thus does not represent logits. Was this intended?
  output, from_logits = _get_logits(


1875/1875 [==============================] - 8s 3ms/step - loss: 0.4326 - accuracy: 0.8727
Epoch 2/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.1990 - accuracy: 0.9457
Epoch 3/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.1597 - accuracy: 0.9560
Epoch 4/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.1350 - accuracy: 0.9624
Epoch 5/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.1184 - accuracy: 0.9673


In [18]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 1s - loss: 0.0949 - accuracy: 0.9756 - 655ms/epoch - 2ms/step


[0.09490399062633514, 0.975600004196167]

In [11]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [12]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[5.7214460e-09, 7.6927416e-11, 1.0732803e-05, 1.0105013e-05,
        2.2069718e-12, 3.9153988e-08, 3.5882742e-15, 9.9997675e-01,
        4.5757929e-08, 2.2919071e-06],
       [8.5240544e-07, 5.5836822e-04, 9.9940407e-01, 2.5547057e-05,
        8.4299959e-16, 1.0671995e-05, 2.2211642e-08, 6.8177174e-14,
        4.2966900e-07, 3.9095338e-14],
       [6.8845492e-07, 9.9816018e-01, 1.3507655e-04, 6.3714499e-05,
        1.5371968e-05, 2.3644636e-05, 3.5243224e-06, 1.4324242e-03,
        1.5368078e-04, 1.1641400e-05],
       [9.9989009e-01, 2.0718325e-09, 3.9241073e-05, 5.9412411e-08,
        8.1380023e-08, 1.6833837e-06, 3.7095542e-06, 9.6668837e-06,
        4.3344990e-09, 5.5430901e-05],
       [8.0219543e-06, 3.3126542e-09, 1.9479094e-06, 1.5980834e-07,
        9.9481440e-01, 7.1228201e-06, 8.3044442e-06, 3.7509304e-05,
        2.3482430e-06, 5.1202597e-03]], dtype=float32)>