<a href="https://colab.research.google.com/github/Keyrama/Machine-Learning/blob/main/Keras_ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.15.0


In [4]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

In [5]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [6]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.04913245, -0.24142326, -0.15402623, -0.1331318 , -0.11464912,
         0.41250437, -0.15751435, -0.37430564,  0.5178182 , -0.35398132]],
      dtype=float32)

In [7]:
tf.nn.softmax(predictions).numpy()

array([[0.09720083, 0.08019719, 0.08752159, 0.08936955, 0.09103669,
        0.15422556, 0.08721684, 0.07021811, 0.17135373, 0.07165984]],
      dtype=float32)

In [8]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [9]:
loss_fn(y_train[:1], predictions).numpy()

1.8693392

In [10]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [11]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 9s 4ms/step - loss: 0.2964 - accuracy: 0.9138
Epoch 2/5
1875/1875 [==============================] - 9s 5ms/step - loss: 0.1441 - accuracy: 0.9577
Epoch 3/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.1083 - accuracy: 0.9677
Epoch 4/5
1875/1875 [==============================] - 9s 5ms/step - loss: 0.0889 - accuracy: 0.9728
Epoch 5/5
1875/1875 [==============================] - 9s 5ms/step - loss: 0.0759 - accuracy: 0.9764


In [12]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 1s - loss: 0.0771 - accuracy: 0.9760 - 644ms/epoch - 2ms/step


[0.07705754041671753, 0.9760000109672546]

In [13]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [14]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[7.4856914e-08, 2.7053833e-08, 5.4550095e-05, 9.9755707e-04,
        6.9079277e-11, 1.8122539e-07, 6.1794656e-13, 9.9894470e-01,
        8.2070221e-07, 2.0741688e-06],
       [1.0916013e-09, 2.2312457e-05, 9.9997509e-01, 1.9821825e-07,
        1.0954925e-14, 1.5339114e-06, 2.5612652e-09, 2.4765999e-12,
        8.0678490e-07, 3.7872177e-13],
       [3.3093397e-07, 9.9843687e-01, 1.9900153e-04, 2.0430547e-05,
        1.6123375e-05, 3.6524973e-05, 3.8953080e-05, 4.5873219e-04,
        7.9257996e-04, 5.2742780e-07],
       [9.9990547e-01, 6.5004540e-09, 2.1544582e-05, 7.4075888e-06,
        2.7861938e-07, 6.6061698e-06, 4.5581786e-05, 1.1464862e-05,
        1.7548039e-07, 1.4506530e-06],
       [1.9042886e-06, 3.7815449e-09, 2.1453672e-05, 2.8131043e-07,
        9.9600440e-01, 1.8435493e-07, 5.8607435e-07, 1.0236575e-04,
        1.6374247e-06, 3.8671044e-03]], dtype=float32)>